<a href="https://colab.research.google.com/github/runjhunratawal/ML-AI-Club-GDSC/blob/main/Naive_Bayes_Mushrooms_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn import preprocessing

In [ ]:
df = pd.read_csv("mushrooms.csv")
df

     class cap-shape cap-surface  ... spore-print-color population habitat
0        p         x           s  ...                 k          s       u
1        e         x           s  ...                 n          n       g
2        e         b           s  ...                 n          n       m
3        p         x           y  ...                 k          s       u
4        e         x           s  ...                 n          a       g
...    ...       ...         ...  ...               ...        ...     ...
8119     e         k           s  ...                 b          c       l
8120     e         x           s  ...                 b          v       l
8121     e         f           s  ...                 b          c       l
8122     p         k           y  ...                 w          v       l
8123     e         x           s  ...                 o          c       l

[8124 rows x 23 columns]

In [ ]:
df.shape

(8124, 23)

In [ ]:
df.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [ ]:
df2 = df.apply(label_encoder.fit_transform)
df2

# Here 0 = Edible Class and 1 = Poisonous Class

      class  cap-shape  cap-surface  ...  spore-print-color  population  habitat
0         1          5            2  ...                  2           3        5
1         0          5            2  ...                  3           2        1
2         0          0            2  ...                  3           2        3
3         1          5            3  ...                  2           3        5
4         0          5            2  ...                  3           0        1
...     ...        ...          ...  ...                ...         ...      ...
8119      0          3            2  ...                  0           1        2
8120      0          5            2  ...                  0           4        2
8121      0          2            2  ...                  0           1        2
8122      1          3            3  ...                  7           4        2
8123      0          5            2  ...                  4           1        2

[8124 rows x 23 columns]

In [ ]:
# Splitting Data into training and testing

y = df2["class"].values
x = df2.drop(["class"],axis=1)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state=False)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(6093, 22)
(2031, 22)
(6093,)
(2031,)

In [ ]:
#Naive Bayes

gnb = GaussianNB()
gnb.fit(x_train,y_train)

print("Accuracy: {}%".format(round(gnb.score(x_test,y_test)*100,2)))

Accuracy: 91.43%

In [ ]:
metrics.classification_report(y_train,y_test)

ValueError: ignored

In [ ]:
metrics.classification_report?